import Link from "next/link";
import type { LucideIcon } from "lucide-react";
import {ArrowRight,Bot,BriefcaseBusiness,Building2,CheckCircle2,CloudCog,Code2,Database,Gauge,Globe2,Layers3,Network,Rocket,ShieldCheck,ShoppingBag,Sparkles,Workflow,Wrench} from "lucide-react";
export const pillars=[{slug:"web-ecommerce",title:"Web & E-commerce",description:"Sites premium, boutiques, plateformes de réservation et expériences digitales performantes.",icon:Globe2},{slug:"applications-saas",title:"Applications & SaaS",description:"Applications métier, MVP, portails privés et produits SaaS fiables et évolutifs.",icon:Code2},{slug:"intelligence-artificielle",title:"Intelligence artificielle",description:"Assistants, agents, chatbots, systèmes documentaires et solutions IA spécialisées.",icon:Bot},{slug:"automatisation-integrations",title:"Automatisation & Intégrations",description:"Workflows, connecteurs et automatisations qui réduisent les tâches répétitives.",icon:Workflow},{slug:"data-infrastructure",title:"Data & Infrastructure",description:"Données, tableaux de bord, cloud, sécurité, performance et déploiement.",icon:Database},{slug:"conseil-maintenance-formation",title:"Conseil, maintenance & formation",description:"Audit, stratégie, support, maintenance continue et montée en compétence des équipes.",icon:Wrench}] as const;
export const navItems=[{href:"/services",label:"Services"},{href:"/solutions",label:"Solutions"},{href:"/methode",label:"Méthode"},{href:"/realisations",label:"Réalisations"},{href:"/a-propos",label:"À propos"},{href:"/contact",label:"Contact"}] as const;
export const iconMap:Record<string,LucideIcon>={Globe2,Code2,Bot,Workflow,Database,Wrench,Rocket,ShieldCheck,Gauge,CloudCog,Network,Layers3,ShoppingBag,Sparkles,Building2,BriefcaseBusiness};
export function Eyebrow({children}:{children:React.ReactNode}){return <span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-emerald-700 shadow-sm"><Sparkles className="h-3.5 w-3.5"/>{children}</span>}
export function SectionHeading({eyebrow,title,text,align="center"}:{eyebrow:string;title:string;text?:string;align?:"left"|"center"}){return <div className={align==="center"?"mx-auto max-w-5xl text-center":"max-w-4xl"}><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-6 text-balance text-[clamp(2.7rem,5vw,5.4rem)] font-semibold leading-[1] tracking-[-.05em] text-[var(--kx-text)]">{title}</h2>{text?<p className={`mt-5 max-w-3xl text-balance text-lg leading-8 text-[var(--kx-muted)] ${align==="center"?"mx-auto":""}`}>{text}</p>:null}</div>}
export function PillarGrid(){return <div className="mt-14 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{pillars.map(({slug,title,description,icon:Icon},index)=><Link key={slug} href={`/services/${slug}`} className={`kx-card kx-reveal kx-reveal-${Math.min(index+1,4)} group rounded-[1.75rem] p-7 sm:p-8`}><div className="flex items-start justify-between gap-4"><span className="kx-glow flex h-13 w-13 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600"><Icon className="h-5 w-5"/></span><span className="font-mono text-xs font-bold tracking-[.16em] text-emerald-600">0{index+1}</span></div><h3 className="mt-10 text-2xl font-semibold tracking-[-.025em] text-[var(--kx-text)]">{title}</h3><p className="mt-4 text-sm leading-7 text-[var(--kx-muted)]">{description}</p><span className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Explorer <ArrowRight className="h-4 w-4 transition duration-300 group-hover:translate-x-1"/></span></Link>)}</div>}
export function PremiumCta({title="Transformons votre idée en système utile.",text="Parlez-nous de votre besoin. Nous vous aidons à cadrer la bonne solution avant de construire."}:{title?:string;text?:string}){return <section className="relative overflow-hidden rounded-[2rem] border border-emerald-100 bg-gradient-to-br from-white via-emerald-50 to-green-100 px-6 py-12 shadow-[0_26px_70px_rgba(0,168,107,.12)] sm:px-10 sm:py-16 lg:px-16"><div className="kx-noise absolute inset-0 opacity-25"/><div className="relative grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-emerald-600">KORYXA Service IA & Web</p><h2 className="mt-4 text-[clamp(2.5rem,4.5vw,4.8rem)] font-semibold leading-[1] tracking-[-.045em] text-[var(--kx-text)]">{title}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[var(--kx-muted)]">{text}</p></div><Link href="/demarrer-un-projet" className="kx-shimmer inline-flex min-h-13 items-center justify-center gap-2 rounded-full bg-[#00a86b] px-7 py-3 font-bold text-white shadow-[0_16px_36px_rgba(0,168,107,.24)] transition hover:-translate-y-1 hover:bg-[#16bc79]">Démarrer un projet <ArrowRight className="h-4 w-4"/></Link></div></section>}
export function CheckList({items}:{items:string[]}){return <ul className="grid gap-3 sm:grid-cols-2">{items.map(item=><li key={item} className="kx-card flex gap-3 rounded-2xl p-4 text-sm font-medium text-[var(--kx-muted)]"><CheckCircle2 className="mt-.5 h-4 w-4 shrink-0 text-emerald-600"/>{item}</li>)}</ul>}
