import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { notFound } from "next/navigation";
import { PremiumCta, SectionHeading } from "@/components/marketing/ServiceMarketing";
import { ServiceCard } from "@/components/services/ServiceCards";
import { getPillar, getPillarServices, servicePillars } from "@/lib/services/catalog";

export function generateStaticParams(){ return servicePillars.map(p => ({ pillar: p.slug })); }
export async function generateMetadata({params}:{params:Promise<{pillar:string}>}):Promise<Metadata>{const {pillar}=await params;const p=getPillar(pillar);return p?{title:`${p.title} | KORYXA`,description:p.description}:{title:"Service introuvable"};}
export default async function PillarPage({params}:{params:Promise<{pillar:string}>}){const {pillar}=await params;const p=getPillar(pillar);if(!p)notFound();const services=getPillarServices(pillar);return <div className="space-y-20"><section className="pt-8 sm:pt-14"><Link href="/services" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-emerald-700"><ArrowLeft className="h-4 w-4"/>Tous les services</Link><div className="mt-8"><SectionHeading eyebrow="Pôle d’expertise" title={p.title} text={p.description}/></div><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{services.map(s=><ServiceCard key={s.slug} service={s}/>)}</div></section><section className="rounded-[2rem] border border-slate-200 bg-white p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-700">Approche KORYXA</p><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><h2 className="text-3xl font-semibold tracking-[-.04em] text-slate-950">Un pôle complet, une exécution coordonnée.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Nous pouvons intervenir sur un service précis ou combiner plusieurs expertises pour construire une solution cohérente de bout en bout.</p></div><Link href={`/demarrer-un-projet?pole=${p.slug}`} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-white px-6 font-bold text-[var(--kx-text)]">Présenter mon besoin <ArrowRight className="h-4 w-4"/></Link></div></section><PremiumCta/></div>}
